name: Generate Snake Game

on:
  push:
    branches:
      - main

jobs:
  generate-snake-game:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate Snake Game from GitHub Contribution Grid
      uses: Platane/snk@v3.2.0
      with:
        github_user_name: 'Guilherme220501'  # Seu nome de usu√°rio do GitHub
        outputs: 'github-contribution-grid-snake.svg'
    
    - name: Commit and push generated snake
      uses: EndBug/add-and-commit@v7
      with:
        author_name: 'GitHub Actions'
        author_email: 'actions@github.com'
        message: 'Generated snake game'
        add: './github-contribution-grid-snake.svg'

